project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - connect.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

