project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - connect.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

